services:
  backend:
    image: ubuntu:24.04
    expose:
      - "8090"
    ports:
      - "8090:8090"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: /app/pocketbase serve --http="0.0.0.0:8090"
